name: Build & deploy API

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/*"
  pull_request:
    branches: [$default-branch]

jobs:
  build-api:
    runs-on: Ubuntu-20.04

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run lint
      - run: npm run build
