name: Build infra code
on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/*"
  pull_request:
jobs:
  build-infra-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: infra/main.bicep

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show deployment plan
        uses: azure/CLI@v1
        env:
          RG: ${{ secrets.AZURE_RG }}
          SUB_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        with:
          azcliversion: 2.16.0
          inlineScript: |
            az deployment group what-if --parameters "tenantId=$TENANT_ID" --resource-group "$RG" --subscription "$SUB_ID" --template-file ./infra/main.json
